language: ruby
rvm:
  - 2.4.1
sudo: false
install: bundle install
script: production bundle exec jekyll build
deploy:
  provider: s3
  access_key_id: $S3_ACCESS_KEY_ID
  secret_access_key: $S3_SECRET_KEY
  bucket: www.mccraw.me
  local_dir: _site
  region: us-east-1
  skip_cleanup: true
  on:
    repo: bmccraw86/mccraw_me
