language: ruby
rvm:
  - 2.4.1
env:
  - JEKYLL_VERSION=3.6.2
sudo: false
install: gem install jekyll -v $JEKYLL_VERSION
script: jekyll build
deploy:
  provider: s3
  access_key_id: $S3_ACCESS_KEY_ID
  secret_access_key: $S3_SECRET_KEY
  bucket: www.mccraw.me
  local_dir: _site
  region: us-east-1
  skip_cleanup: true
  on:
    repo: bmccraw86/mccraw_me
